version: "3"
services:
  golang:
    build: ./golang
    ports:
      - "8088:8088"
    links:
      - "mysql"
      - "redis"
    volumes:
      - d:\coding/go:/go
      - d:\coding/goroot:/usr/local/go  
    tty: true
    container_name: golang
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
     # - /home/code/data/golang-mysql/:/var/lib/mysql/
      - d:\coding/data:/data
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql  
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
