version: '3'
services:
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "phpmyadmin"
    ports:
     - "9090:80"
    environment:
     - PMA_ARBITRARY=1
  db:
    image: "mysql:5.7"
    container_name: "phpmyadmin_db"
