# web server
nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "80:80"
    - "8080:8080"  
  volumes:
   #- $HOME/code/php/www:/source
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
  links:
    - fpm:__DOCKER_PHP_FPM__

golang:
  image: golang:latest
  container_name: golang
  # command: apt-get update && apt-get install -y vim
  ports:
    - "9090:9090"
  links:
    - "mysql"
    - "redis"
  volumes:
    - $HOME/code/go:/go
  tty: true

# php-fpm
fpm:
  image: registry.cn-shenzhen.aliyuncs.com/yxw-docker/php
  container_name: php
  ports:
    - "9000"
  links:
    - mysql:mysql
    - redis:redis
  volumes:
    - $HOME/code/php:/source
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
    - ./php-fpm/cron/laravel:/var/spool/cron/crontabs/laravel
    - ./php-fpm/supervisor/program.conf:/etc/supervisor/conf.d/program.conf
  command: supervisord -c /etc/supervisor/supervisord.conf

# database
mysql:
  image: mysql:5.7
  container_name: mysql
  ports:
    - "3306:3306"
 #volumes:
   #- $HOME/code/data/mysql:/var/lib/mysql
   #- ./my.cnf:/etc/mysql/conf.d/my.cnf
  environment:
    - MYSQL_ROOT_PASSWORD=123456789

redis:
  image: redis:3
  container_name: redis
  command: redis-server /usr/local/etc/redis/redis.conf --requirepass 123456789
  volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  ports:
    - "6379:6379"
phpmyadmin:
  image: "phpmyadmin/phpmyadmin"
  container_name: "phpmyadmin"
  ports:
   - "9191:80"
  environment:
   - PMA_ARBITRARY=1 
